#' Merges results of ODAparse into printable report.
#'
#' @description Transforms objects created by \code{ODAparse} and loads results.
#'
#' @param run The numerical value of the run folder in which the data file is
#'   stored
#' @param ... Additional run numbers specified as a list
#'
#' @details When run, \code{ODAsummary} will merge the ODA model summary and
#'   model performance metrics that are stored in the global environment.
#'
#'   The \code{run} number should be an existing run file within the current
#'   project tree. To function properly, \code{ODAparse} must first be completed
#'   for each run for which a summary report is being requested.
#'
#'   For more information on the objects generated by \code{ODAparse} see
#'   documentation for \code{ODAparse}. Specifically, \code{ODAsummary} will
#'   merge the object "oda.model.X" and "oda.perf.X" where X is the \code{run}
#'   number specified as an argument to \code{ODAparse} and \code{ODAsummary}.
#'
#'   The "oda.summary.X" object also includes several new variables each of
#'   which indicate whether the model results are significant in training
#'   "mcpsig" or LOO "loosig" or LOO-stable "loostab" indicating the ESS in
#'   training is the same as the ESS in LOO.
#'
#'   For models where loooff=T, "loostab" and "loosig" are not reported, see
#'   \code{ODArun} for more details on LOO specifications.
#'
#'   For GEN models, the report is limited to the overall model. Users should
#'   review the \code{ODAparse} outputs and the "oda.model.X" summary object to
#'   evaluate the results for each GEN sample / subgroup.
#'
#' @return The following objects are returned for ODA models:
#'   \item{oda.summary.X}{Merged Object containing "oda.model.X" and
#'   "oda.perf.X" where X is specified by the \code{run} argument.}
#'
#' @export
#'
#' @author Nathaniel J. Rhodes
#'
#' @seealso \code{\link{ODAmanual}} \code{\link{ODAparse}} \code{\link{ODArun}}
#'
#' @examples
#'
#' #' # Not run:
#' # ODAsummary(1)
#' # print(oda.summary.1)
#'
ODAsummary <- function(run="",...) {
  if(run==""){
    stop(
      print("Message: User must specify a run number of the ODAparse results to load.\n")
    )
  }
  else {
    addlruns <- list(...)
  }
  if (length(addlruns) > 0) {
    allruns <- c(run, unlist(addlruns))
  }
  else {
    allruns <- run
  }
  msumm <- list()
  for (thisrun in allruns){
    model <- paste0("oda.model.",thisrun)

    perf <- paste0("oda.perf.",thisrun)

    if(exists(model) & exists(perf)){

      model <- get0(model)

      perf <- get0(perf)

      perf.names <- colnames(perf)

      perf <- as.data.frame(matrix(unlist(perf),nrow=nrow(perf),byrow=F),stringsAsFactors = F)

      colnames(perf) <- perf.names

      colnames(model) <- gsub("*\\(%\\)",":",colnames(model))

      model$mcpsig <- ifelse(as.numeric(as.character(model$`MC P-value`)) <= 0.05,1,0)

      if("LOO P-value:" %in% colnames(model)){
        model$loosig <- ifelse(as.numeric(as.character(model$`LOO P-value:`)) <= 0.05,1,0)
        model$loostab <- ifelse(model$`Overall ESS:` %in% model$`LOO ESS:`,1,0)
      } else{cat("LOO not specified in model. LOO stablity not evaluated.\n")}

      # If GEN model, report only the overall model for dimensionality to match perf object
      if(length(unique(model$Model))!=nrow(model)){
        model <- model[unique(model$Model),]
      }

      model$Model <- as.numeric(as.character(model$Model))

      msumm[[thisrun]] <- cbind(model,perf)

    }
    else{
      stop(
        paste("The requested oda.perf or oda.model object(s) were not found.\n Run ODAparse() to generate these from a completed ODArun().\n")
      )
    }
  }
  for (thisrun in allruns){
    assign(paste0("oda.summary.",thisrun), msumm[[thisrun]], pos = parent.frame())
  }
}

